name: test-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on : self-hosted
    steps   :
# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: pwd
        run : pwd

      - name: cd
        run : |
          cd /var/www
          actions/checkout@v2
      

